let handler = m => m

handler.before = function (m) {
    let user = global.db.data.users[m.sender]
    let role = (user.level <= 3) ? '𝐆𝐮𝐞𝐫𝐫𝐞𝐫𝐨 𝐕'
      : ((user.level >= 3) && (user.level <= 6)) ? '𝐆𝐮𝐞𝐫𝐫𝐞𝐫𝐨 𝐈𝐕'
      : ((user.level >= 6) && (user.level <= 9)) ? '𝐆𝐮𝐞𝐫𝐫𝐞𝐫𝐨 𝐈𝐈𝐈'
      : ((user.level >= 9) && (user.level <= 12)) ? '𝐆𝐮𝐞𝐫𝐫𝐞𝐫𝐨 𝐈𝐈'
      : ((user.level >= 12) && (user.level <= 15)) ? '𝐆𝐮𝐞𝐫𝐫𝐞𝐫𝐨 𝐈'
      : ((user.level >= 15) && (user.level <= 18)) ? 'É𝐥𝐢𝐭𝐞 𝐕'
      : ((user.level >= 18) && (user.level <= 21)) ? 'É𝐥𝐢𝐭𝐞 𝐈𝐕'
      : ((user.level >= 21) && (user.level <= 24)) ? 'É𝐥𝐢𝐭𝐞 𝐈𝐈𝐈'
      : ((user.level >= 24) && (user.level <= 27)) ? 'É𝐥𝐢𝐭𝐞 𝐈𝐈'
      : ((user.level >= 27) && (user.level <= 30)) ? 'É𝐥𝐢𝐭𝐞 𝐈'
      : ((user.level >= 30) && (user.level <= 33)) ? '𝐌𝐚𝐞𝐬𝐭𝐫𝐨𝐬 𝐕'
      : ((user.level >= 33) && (user.level <= 36)) ? '𝐌𝐚𝐞𝐬𝐭𝐫𝐨𝐬 𝐈𝐕'
      : ((user.level >= 36) && (user.level <= 39)) ? '𝐌𝐚𝐞𝐬𝐭𝐫𝐨𝐬 𝐈𝐈𝐈'
      : ((user.level >= 39) && (user.level <= 42)) ? '𝐌𝐚𝐞𝐬𝐭𝐫𝐨𝐬 𝐈𝐈'
      : ((user.level >= 42) && (user.level <= 45)) ? '𝐌𝐚𝐞𝐬𝐭𝐫𝐨𝐬 𝐈'
      : ((user.level >= 45) && (user.level <= 48)) ? '𝐆𝐫𝐚𝐧 𝐌𝐚𝐞𝐬𝐭𝐫𝐨 𝐕'
      : ((user.level >= 48) && (user.level <= 51)) ? '𝐆𝐫𝐚𝐧 𝐌𝐚𝐞𝐬𝐭𝐫𝐨 𝐈𝐕'
      : ((user.level >= 51) && (user.level <= 54)) ? '𝐆𝐫𝐚𝐧 𝐌𝐚𝐞𝐬𝐭𝐫𝐨 𝐈𝐈𝐈'
      : ((user.level >= 54) && (user.level <= 57)) ? '𝐆𝐫𝐚𝐧 𝐌𝐚𝐞𝐬𝐭𝐫𝐨 𝐈𝐈'
      : ((user.level >= 57) && (user.level <= 60)) ? '𝐆𝐫𝐚𝐧 𝐌𝐚𝐞𝐬𝐭𝐫𝐨 𝐈'
      : ((user.level >= 60) && (user.level <= 63)) ? 'É𝐩𝐢𝐜𝐨 𝐕'
      : ((user.level >= 63) && (user.level <= 66)) ? 'É𝐩𝐢𝐜𝐨 𝐈𝐕'
      : ((user.level >= 66) && (user.level <= 69)) ? 'É𝐩𝐢𝐜𝐨 𝐈𝐈𝐈'
      : ((user.level >= 69) && (user.level <= 71)) ? 'É𝐩𝐢𝐜𝐨 𝐈𝐈'
      : ((user.level >= 71) && (user.level <= 74)) ? 'É𝐩𝐢𝐜𝐨 𝐈'
      : ((user.level >= 74) && (user.level <= 77)) ? '𝐋𝐞𝐲𝐞𝐧𝐝𝐚 𝐕'
      : ((user.level >= 77) && (user.level <= 80)) ? '𝐋𝐞𝐲𝐞𝐧𝐝𝐚 𝐈𝐕'
      : ((user.level >= 80) && (user.level <= 83)) ? '𝐋𝐞𝐲𝐞𝐧𝐝𝐚 𝐈𝐈𝐈'
      : ((user.level >= 83) && (user.level <= 86)) ? '𝐋𝐞𝐲𝐞𝐧𝐝𝐚 𝐈𝐈'
      : ((user.level >= 86) && (user.level <= 89)) ? '𝐋𝐞𝐲𝐞𝐧𝐝𝐚 𝐈'
      : ((user.level >= 89) && (user.level <= 91)) ? '𝐌í𝐭𝐢𝐜𝐨 𝐕'
      : ((user.level >= 91) && (user.level <= 94)) ? '𝐌í𝐭𝐢𝐜𝐨 𝐈𝐕'
      : ((user.level >= 94) && (user.level <= 97)) ? '𝐌í𝐭𝐢𝐜𝐨 𝐈𝐈𝐈'
      : ((user.level >= 97) && (user.level <= 100)) ? '𝐌í𝐭𝐢𝐜𝐨 𝐈𝐈'
      : ((user.level >= 100) && (user.level <= 105)) ? '𝐌í𝐭𝐢𝐜𝐨 𝐈'      
      : ((user.level >= 105) && (user.level <= 120)) ? '𝐆𝐥𝐨𝐫𝐢𝐚 𝐌í𝐭𝐢𝐜𝐚'
      : ((user.level >= 120) && (user.level <= 150)) ? '𝐄𝐬𝐦𝐞𝐫𝐚𝐥𝐝𝐚 𝐕'
      : ((user.level >= 150) && (user.level <= 160)) ? '𝐄𝐬𝐦𝐞𝐫𝐚𝐥𝐝𝐚 𝐈𝐕'
      : ((user.level >= 160) && (user.level <= 170)) ? '𝐄𝐬𝐦𝐞𝐫𝐚𝐥𝐝𝐚 𝐈𝐈𝐈'
      : ((user.level >= 170) && (user.level <= 185)) ? '𝐄𝐬𝐦𝐞𝐫𝐚𝐥𝐝𝐚 𝐈𝐈'
      : ((user.level >= 185) && (user.level <= 200)) ? '𝐄𝐬𝐦𝐞𝐫𝐚𝐥𝐝𝐚 𝐈'
      : ((user.level >= 200) && (user.level <= 400)) ? '𝐓𝐢𝐭𝐚𝐧 𝐈𝐈𝐈'
      : ((user.level >= 405) && (user.level <= 700)) ? '𝐓𝐢𝐭𝐚𝐧 𝐈𝐈'
      : ((user.level >= 700) && (user.level <= 1000)) ? '𝐓𝐢𝐭𝐚𝐧 𝐈'
      : '𝐃𝐫𝐚𝐠𝐨𝐧 𝐫𝐞𝐲 𝐞𝐬𝐭𝐫𝐞𝐥𝐥𝐚'

    user.role = role
    return true
}

export default handler
